### ISSUE TITLE
Batch Process: Create a prototype a la leihs helper

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#103]

**Comment by phiku** [comment]
Work in progress: 

![bildschirmfoto 2018-07-16 um 15 47 38](https://user-images.githubusercontent.com/16756048/42762120-b7ed3afc-890f-11e8-86b5-26d843509a59.png)

Meta data editable for media entries and collections. Also applicable only for a selection. Todo is to make sure what happens when we have meta data which is only allowed for media entries mixed with meta data which is only for collections.

**Comment by phiku** [comment]
@nadjaweisskopf
There is a fully working prototype for editing meta data on:
https://test-blank.madek.zhdk.ch

There is one functionality missing. When there occurs an error for one of the entries/sets which are saved (e.g. connection is lost), there is not yet an error message and no retry button. 

Otherwise the functionality should be complete to work with. There is for example no date picker for dates. But since the dates are only texts, it works so far correctly. It is also not yet possible to delete data or add keywords (instead of replace). But what we have so far should be working without errors or restrictions.

**Comment by phiku** [comment]
@nadjaweisskopf Just realized, that there is something missing when I was testing. There is no check at the moment, if you are allowed to update the media entries. It just tries, but it fails on the server. So this is a missing point.

**Comment by phiku** [comment]
Todo: For the apply buttons subract the not editable resources.

**Comment by phiku** [comment]
@nadjaweisskopf 
Es gibt noch ein Problem für ein Refinement. Im Moment werden für den Medienersteller einige Daten zusammengefasst. Dies geschieht in den Server Settings, nicht im Admin. Das ist nur für die ZHdK.
![bildschirmfoto 2018-07-25 um 09 37 04](https://user-images.githubusercontent.com/16756048/43186204-4cdb0358-8fee-11e8-8034-2ef881e80aec.png)
 

Wenn ich das nicht mache, dann sehen die Meta Keys wie folgt aus: 

![bildschirmfoto 2018-07-25 um 09 35 20](https://user-images.githubusercontent.com/16756048/43186155-32e7e628-8fee-11e8-89f0-4d9108d1d84e.png)


Das ganze ist ein konzeptionelles Problem. Es steht da nun z.B. "Stadt". Eigentlich müsste das "Medienersteller Stadt" heissen. Sonst weiss man nicht was der Key genau bedeutet. Oder aber man macht ein Vokabular "Medienersteller". Prinzipiell ist unklar wie man in Zukunft damit umgeht.

**Comment by cmonstein** [comment]
[TestfeedbackQuickRun.pdf](https://github.com/Madek/madek/files/2245511/TestfeedbackQuickRun.pdf)
Anbei mein Feedback, LG Claudia
