### ISSUE TITLE
Sonderbare Wortergänzung im Schlagwort-Feld

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#122]
The Suggestions of the field "Keywords" are very crazy. Suggestions start whatever vacales letter we put it incorrect. More inforamtion in Printscreen. 
**************************************************************************************
Das Feld «Schlagworte» ergänzt die Eingabe sonderbar: Vorschläge beginnen erst mit I, egal welch Buchstabe eingetragen wird:
![image](https://user-images.githubusercontent.com/42544602/45959021-33c40580-c019-11e8-8b0d-ef4642ed4e16.png)

In Field "Material / Format / Language" the complementation are correctly. 
*****************************************************************
Im Feld «Material / Format / Sprache» ist die Ergänzung korrekt:
![image](https://user-images.githubusercontent.com/42544602/45959124-74238380-c019-11e8-82b4-1c7f237d5074.png)

**Comment by nadjaweisskopf** [comment]
Michal um Analyse bitten

**Comment by michalpodlecki** [comment]
Keywords after searching are additionaly sorted by relevance, and there are four rules which compute the rank needed for sorting mechanism.

The «Schlagworte» meta key contains 9743 keywords, when «Material / Format / Sprache» meta keys contains "only" in quotes 283 keywords,
so there is an obvious situation, that sorting results for the second one are less vulnerable (walnerabl) for edge cases.

In my opinion the solution could be about adding some condition, when the sorting rules are applied at all, I mean when you type a term with length equal or greater than 2 letters. Because the issue happens only for 1-letter term.

**Comment by nadjaweisskopf** [comment]
@michalpodlecki Matus and Michal will check if the sorting of the results can be optimised before we adjust the minimum letters to be entered before giving a result to 3.

**Comment by nadjaweisskopf** [comment]
closed because ticket has been developed. @phoettli please reopen the ticket, if you find bugs.

**Comment by phoettli** [comment]
still strange behaviour:
![image](https://user-images.githubusercontent.com/42544602/47348839-9eb53a80-d6b2-11e8-9b3c-4ea3427b4e30.png)

**Comment by nadjaweisskopf** [comment]
@michalpodlecki Michal, Did you have a chance to check Philipps feedback?

**Comment by michalpodlecki** [comment]
@nadjaweisskopf not yet, I was focused on Roles feature, I'll make an update today

**Comment by phoettli** [comment]
Reihenfolge ist noch immer sehr verwunderlich: oft kommen erst Wortergänzungen, bei denen der Suchvorschlag im Wortinnern auftritt, statt am Wortanfang.
Immerhin aber schon etwas besser jetzt als vorher, die ganz schlimmen Fehler sind weg.

Ich schliesse dieses Ticket erstmal, ggf. bei Perfektionsanspruch wieder öffenen.
