### ISSUE TITLE
Stapelverarbeitung zeigt keine gemischten Werte an 

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#232]
Innerhalb des Sets bei Editierung aller Inhalte oder Stapelverarbeitung möchte der User Metadaten editieren, hier _Mitwirkende/ Beteiligte Personen_. 

**Problem:** der edit-mode zeigt keine gemischten Werte bei _Mitwirkende/ Beteiligte Personen_ an, das führt zu einer unbeabsichtigten Überschreibung von bereits bestehenden Werten in _Mitwirkende/ Beteiligte Personen_. Aktuell zeigt das Feld einen einzigen Wert aus dem Stapel an, obwohl es weitere Werte (beteiligte Personen) gäbe

![1  Set-Ansicht mit versch  Personen](https://user-images.githubusercontent.com/29139407/74654138-ed30f700-5189-11ea-8e02-32260aae3e4f.jpg)

![2  Metadaten editieren](https://user-images.githubusercontent.com/29139407/74654157-fb7f1300-5189-11ea-8d02-1da524da7cef.jpg)

Hinweis: folgendes Set verfügt über Audios mit verschiedenen Werten zu _Mitwirkende/ Beteiligte Personen_   
https://test.madek.zhdk.ch/sets/75c0e669-c7e7-40fb-b0d6-a4f954bd741e

**Comment by phoettli** [comment]
soweit ich das verstehe, bleibt eine "beliebige" Person hängen aus einem der angewählten Datensätzen. Beim Abspeichern bekommen dann alle Datensätze im Stapel diesen Wert zugeschrieben.

**Comment by eins78** [comment]
problematic code is here: there is a large SQL query to find out something like a "diff status", that needs to be extended to work with the newly added metadatum types.
https://github.com/Madek/madek-webapp/blob/3d15446df53971b5ba13ff6abcb7828b457b2fea/app/presenters/presenters/media_entries/batch_diff_query.rb#L62-L101

I added some fake data to verify that the UI would behave correctly with it (for the example from start of this issue). This also shows the shape of the expected output:

```ruby
      def self.diff(clazz, initial_scope)
        res = run diff_query(clazz, initial_scope)
        res.push({
          "meta_key_id" => "media_object:creative_participants_roles",
          "max" => 3,
          "count" => 24})
        res
      end
```

fixes:
- [ ] add  unit tests for this method. create a bunch of MDs with and without differences and then `expect` the counts to be correct.

- [ ] protect against this mistake: make i throw when there is an unhandled MD type in the selection. something like `select distinct meta_datum.type …` and checking this againt a hardcoded list should be enough. be careful with performance tho.

- [ ] handle `Metadatum::Roles` (similar to Keywords)

- [ ] handle `Metadatum::JSON` (extending the Text and TextDate queries)

- [ ] handle `Metadatum::MediaEntry` (or prepare to, since its not yet merged)
