### ISSUE TITLE
manual sorting does not work in different sets

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#291]
### Ausgangslage
- Medieneinträge können in mehreren Sets unabhängig voneinander gruppiert werden.
- Medieneinträge können in einem Set manuell sortiert werden.

### Problem

1. Die manuelle Sortierung in einem Set, sortiert auch die Medieneinträge in allen anderen Sets, in denen diese Medieneinträge enthalten sind. Das darf nicht sein! In anderen Sets darf die Sortierung nicht tangiert werden.
2. nach Sortierung in verschiedenen Sets, lässt sich die Sortierung nicht mehr verändern.

### Lösung
?

**Comment by phoettli** [comment]
ich habe erstellt:
- vier Medieneinträge in drei verschiedenen Sets ABCD, CBAD, DACB
https://medienarchiv.zhdk.ch/sets/fda413ee-fb3f-4d67-9ae3-347c5e8ea096
https://medienarchiv.zhdk.ch/sets/bd269385-0656-4eab-87fa-8b4fa171b33f
https://medienarchiv.zhdk.ch/sets/24b934e4-0ccf-4c55-b8f2-942901a447e8
![image](https://user-images.githubusercontent.com/42544602/102250762-3c5bcb80-3f04-11eb-837e-88bbb14859ae.png)

- sortiere das Set ABCD manuell der Reihe nach
![image](https://user-images.githubusercontent.com/42544602/102250932-6f05c400-3f04-11eb-9d8b-9cf43815b7d0.png)

- sortiere das Set DACB der Reihe nach
![image](https://user-images.githubusercontent.com/42544602/102250999-85138480-3f04-11eb-9fef-569a1ab35346.png)

=> Das Set ABCD verändert die Reihenfolge. Eine Korrektur der Sortierung ist mir nicht mehr möglich.
![image](https://user-images.githubusercontent.com/42544602/102251238-d4f24b80-3f04-11eb-8226-2477348f8caf.png)

**Comment by eins78** [comment]
minimal reproduction on my machine shows that this a problem with the display of the entries only. the data is saved to and stored correctly in the Database. 
That means the bug should be easy to fix and needs no DB changes/migrations, etc, also we did not loose any data entered by users.
We'll also want to add an integration test for that sceanario.

- first edit position in set B, then in set A. everything is stored correctly.

<img width="3028" alt="Screen Shot 2020-12-16 at 10 19 44" src="https://user-images.githubusercontent.com/134942/102329580-dbc2a200-3f88-11eb-8bbd-8713dc99bce2.png">

- when i refresh the view for set B, the `position` of entry A in set B comes from set A (0 instead of 1)

<img width="1492" alt="Screen Shot 2020-12-16 at 10 22 39" src="https://user-images.githubusercontent.com/134942/102329595-df562900-3f88-11eb-86a9-5c5c82bb0678.png">

**Comment by eins78** [comment]
@michalpodlecki It looks like there is a `WHERE` clause missing that should reference the `collection_id`.
https://github.com/Madek/madek-datalayer/blob/55e53ce4aa3c4147fa3b4eea220edb5a1cb54976/app/models/media_resource.rb#L106-L107

**Comment by eins78** [comment]
fix from @michalpodlecki confirmed 🥇 

https://github.com/Madek/madek/commit/40437c0f517085d54080bfa1f669956923332575

![Uploading Screen Shot 2020-12-17 at 15.37.52.png…]()

**Comment by eins78** [comment]
@phoettli also confirmed on `test` with your examples (I moved all of them around, everything stayed as it should)

<img width="936" alt="Screen Shot 2020-12-17 at 16 23 34" src="https://user-images.githubusercontent.com/134942/102507288-5ae8d080-4084-11eb-85f4-dc30dd453fe9.png">
<img width="950" alt="Screen Shot 2020-12-17 at 16 23 30" src="https://user-images.githubusercontent.com/134942/102507300-5e7c5780-4084-11eb-83e3-d51495fcf1a9.png">
<img width="923" alt="Screen Shot 2020-12-17 at 16 23 24" src="https://user-images.githubusercontent.com/134942/102507305-5fad8480-4084-11eb-89f9-89324f6a935b.png">

**Comment by phoettli** [comment]
OK, super cool !
