### ISSUE TITLE
Remove / Replace libv8 and the rubyracer

### ISSUE THREAD

**Issue by DrTom** [Madek/madek#311]
This stuff is so antiquated that it will not install on  modern MacOS (and probably other OSes too). 

It should be possible to replace it with some modern version of nodejs.

**Comment by eins78** [comment]
some background:
* we need a JS engine for server-side rendering
* `therubyracer` gem provides a wrapper for several JS engines, it supports nodejs but also ruby-specific ones that use `libv8`
* that means the compilation problems are especially bad because we spend time fixing things that aren't used in the end

goal/solution: make SSR work without this gem (see `react-rails` docs for our version)

**Comment by eins78** [comment]
done in https://github.com/Madek/madek/commit/57b03c5e5385da85179dda206c9f1153c41dca8c
(uses `mini_racer` instead, install nodejs anyways)
