### ISSUE TITLE
Workflow: Upload => unvollständig UND vollständig

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#331]
### Ausgangslage

Wenn ein Medieneintrag hochgeladen wird, kommt er zuerst in den Status "unvollständig" bis Pflichtfelder ausgefüllt und einmal abgespeichert.

### Problem

Wenn in einem Workflow ein Medieneintrag hochgeladen wird, ist die Funktion vervollständigen nicht vorgesehen – der Link führt direkt zum Workflow.
Der hochgeladene Medieneintrag erscheint danach doppelt, einmal als unvollständiger Medieneintrag und einmal als vollständiger Medieneintrag:
![image](https://user-images.githubusercontent.com/42544602/118787484-2aa39900-b893-11eb-9f4d-a25ec4a139c6.png)

### Lösung

?
ev. doppelte Aufführung entfernen? entweder – oder.

**Comment by eins78** [comment]
yes, this is a bug. the entry should only appear once, in the "incomplete" section (because it is). 

steps to reproduce/spec that should be added:
* create a workflow
* click "add media" button
* upload an image
* go to the dashboard 
* OK: the image should be listed in "incomplete"
* TO BE FIXED: the image should not be listed under "media entries"

**Comment by phoettli** [comment]
ok auf Staging.
