### ISSUE TITLE
sql injection vulnerability 

### ISSUE THREAD

**Issue by 0xElmalky** [Madek/Madek#552]
I had identified a SQL injection in the a request in madek and had sent you an email and no one replied from a week until now.
i want just to record a cve

**Comment by ugodevito** [comment]
Hello. 

Thanks for your message and sorry for not responding sooner. 

The vulnerability has been reported on January, 21 and fixed in the release [release: v4.2.1](https://github.com/Madek/Madek/commit/ee3073e7aad1edb90b5ad4231e65a7219aab4931) on January, 23.

We have not recorded a cve yet due to internal administrative reasons.

Best regards

**Comment by 0xElmalky** [comment]
Hello, 

Can you reply by mail?
I had sent the E-mail via [support.medienarchiv@zhdk.ch]

**Comment by ugodevito** [comment]
Hi
I don't have access to that mail account, but I'll tell them to reply to you.
Regards

**Comment by phoettli** [comment]
fixed
